Feat/volume task def
TechHoldingLLC/terraform-aws-ecs-task-definition pull request #10
Opened 2024-11-26 06:03 UTC by satyamdudhat2012

2024-11-26 08:37 UTC, kaustubhposhiya requested changes

2024-11-26 08:37 UTC, kaustubhposhiya commented on variables.tf
> +variable "ephemeral_storage_size"{
Format the code and update EXAMPLE.md file for this change.

2024-12-24 10:28 UTC, kaustubhposhiya approved these changes

2024-12-24 10:29 UTC, piyushsonigra approved these changes

2024-12-24 10:32 UTC, merged